Ai pbi's (#379)
* initial try to implement frontend for sending feedback via the thumbs up and down

right now the issue is, that i cant get the userprompt correctly to send it with and same goes for the. other variables:

 WARN  Possible Unhandled Promise Rejection (id: 3):
ReferenceError: Can't find variable: userPrompt
_callee$

* Quick clean up

Fix the call to the feedback button, and changed the variable names

* moved component into parent component and changed its location on the eduscreen

* updated: changed logic to show both buttons if state is null and if one is pressed only that one is showed

* Audio on all messages

* Course context

* Audio to text fix

* translate

* fix lint ready for pr

* Update package-lock.json

* Quick cleanup

* fix null

---------

Co-authored-by: Jenspetersen99 <70944848+Jenspetersen99@users.noreply.github.com>
Co-authored-by: MBryder <mbryde22@student.aau.dk>
Co-authored-by: Gustaw Hagen Juul Jakobsen <gustaw1313@gmail.com>